apiVersion: argoproj.io/v1alpha1 # ArgoCD Application resource
kind: Application
metadata:
  name: node-api-docker-kubernetes-argocd
  namespace: argocd
spec:
  project: default # ArgoCD project name

  source: 
    repoURL: https://github.com/PAIshanMadusha/node-api-docker-kubernetes-argocd.git # Git repository URL
    targetRevision: HEAD
    path: k8s

  destination: 
    server: https://kubernetes.default.svc # In-cluster Kubernetes API server
    namespace: default
  
  syncPolicy: # Enable automated sync
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true